### ISSUE TITLE
Unable to compile on windows.

### ISSUE THREAD

**Issue by Dyrand** [JethroDevon/revengeMusic#33]
Compilation error due to this line in MessageQueue.cpp(22):

`flock.file << tmp.native() << "/" << queue_name << ".lock";`

Caused by std::stringstream

Error:
> C:\Users\Dyrand\Source Code\CppSource\revengeMusic\src\MessageQueue.cpp(22): 
error C2679: binary '<<': 
no operator found which takes a right-hand operand of type 'const boost::filesystem::path::string_type' (or there is no acceptable conversion)
 [C:\Users\Dyrand\Source Code\CppSource\revengeMusic\build\revengeMusic.vcxproj]

Stems from working with non-wide versions of _strings_ and _string_ like objects
For example, std::stringstream has a wide version: std::wstringstream.

**Comment by MonJamp** [comment]
Darn I could've sworn it compiled on Windows, I might have been using MinGW though. So would the solution be to use wide strings?

**Comment by MonJamp** [comment]
@Dyrand because of 973d967 GitHub auto closed your previous pull request due to conflicts (#34). So you're gonna have to look [here](https://github.com/JethroDevon/revengeMusic/commit/033ccdd266e49734770e6ed207f0ddff00daef0d) to see the changes you made. We're pretty close to having our first solid release (v1.0.0); we just need to get this issue fixed and do some testing on the error-check branch.
